### ISSUE TITLE
Suggestion: more key options

### ISSUE THREAD

**Issue by sepsol** [DenisD3D/Keys4Macros#1]
- I usually don't use set time day/night, please add set time noon/midnight too.
- gamerule doDayNightCycle true/false
- gamerule doWeatherCycle true/false
- gamerule keepInventory true/false

Of course if possible, an option to add your own commands would be great, but for now I think the above commands are essential.

**Comment by DenisD3D** [comment]
Thanks for your issue. I will look to a solution to implement that...

**Comment by sepsol** [comment]
Thank you so much!

**Comment by DenisD3D** [comment]
Update uploaded on curseforge....
If you have any other suggestions feel free to open a new issue.
